version: '3.8'

services:
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      PGPASSWORD: '${DB_PASSWORD:-passw0rd}'
      POSTGRES_HOST: '${DB_HOST}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-passw0rd}'
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
  php-fpm:
    container_name: ${PROJECT_NAME}-php-fpm
    build:
      context: ./docker/php-fpm
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    depends_on:
      - postgres
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./app/:/var/www/app/
    ports:
      - "3000:3000"

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www:rw
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"
